-- ==========================================
-- HOCZITA SUPABASE DATABASE SCHEMA
-- ==========================================

-- 1. Kích hoạt Extension UUID nếu chưa có
create extension if not exists "uuid-ossp";

-- 2. Tạo bảng Profiles (Thông tin thành viên)
create table public.profiles (
    id uuid references auth.users on delete cascade primary key,
    username text unique,
    avatar_url text,
    total_score integer default 0,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Bật tính năng Row Level Security (RLS) bảo mật dữ liệu
alter table public.profiles enable row level security;

-- 3. Tạo bảng Game Scores (Lưu lịch sử chơi và điểm số)
create table public.game_scores (
    id bigint generated by default as identity primary key,
    profile_id uuid references public.profiles(id) on delete cascade not null,
    game_name text not null, -- 'flashcard_speed', 'memory_match', 'picture_guess', 'counting', 'math_ops', 'comparison'
    stars integer check (stars >= 1 and stars <= 3) not null,
    score integer default 0 not null,
    completed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Bật tính năng RLS cho bảng điểm số
alter table public.game_scores enable row level security;


-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Chính sách cho bảng Profiles:
-- 1. Cho phép bất kỳ ai đọc thông tin Profile (để hiển thị Bảng xếp hạng - Leaderboard)
create policy "Allow public read access to profiles"
on public.profiles for select
using (true);

-- 2. Chỉ cho phép chính User cập nhật thông tin cá nhân của họ
create policy "Allow individual updates to profiles"
on public.profiles for update
using (auth.uid() = id);


-- Chính sách cho bảng Game Scores:
-- 1. Cho phép bất kỳ ai đọc bảng điểm (phục vụ bảng xếp hạng)
create policy "Allow public read access to game_scores"
on public.game_scores for select
using (true);

-- 2. Chỉ cho phép User đã đăng nhập thêm điểm số của chính mình
create policy "Allow authenticated users to insert their own scores"
on public.game_scores for insert
with check (auth.uid() = profile_id);


-- ==========================================
-- AUTO-PROFILE TRIGGER ON USER SIGNUP
-- ==========================================
-- Hàm tự động tạo hàng mới trong public.profiles khi một tài khoản đăng ký thành công ở auth.users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url, total_score)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)), -- Lấy username từ metadata hoặc dùng phần trước của email
    coalesce(new.raw_user_meta_data->>'avatar_url', null),
    0
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger chạy hàm trên sau khi insert vào auth.users
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- ==========================================
-- AUTO-UPDATE TOTAL SCORE TRIGGER
-- ==========================================
-- Hàm tự động tính toán lại tổng điểm (total_score) của user khi có điểm game mới được lưu
create or replace function public.handle_update_total_score()
returns trigger as $$
begin
  update public.profiles
  set total_score = (
    select coalesce(sum(score), 0)
    from public.game_scores
    where profile_id = new.profile_id
  ),
  updated_at = timezone('utc'::text, now())
  where id = new.profile_id;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger chạy hàm tính tổng điểm sau mỗi lần chèn điểm game mới
create or replace trigger on_game_score_inserted
  after insert on public.game_scores
  for each row execute procedure public.handle_update_total_score();


-- ==========================================
-- 1:1 ADVISING BOOKINGS TABLE & TRIGGERS
-- ==========================================

-- 1. Tạo bảng Bookings (Lịch đặt tư vấn 1:1)
create table if not exists public.bookings (
    id bigint generated by default as identity primary key,
    profile_id uuid references public.profiles(id) on delete set null,
    course text not null,
    booking_time timestamp with time zone not null,
    full_name text not null,
    phone text not null,
    email text not null,
    notes text,
    is_confirmed boolean default false not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Bật tính năng Row Level Security (RLS) bảo mật dữ liệu cho bảng bookings
alter table public.bookings enable row level security;

-- Thêm chính sách bảo mật RLS cho bảng bookings:
-- 1. Cho phép bất kỳ ai chèn bản ghi mới (để khách vãng lai và thành viên đều đặt lịch được)
create policy "Allow anonymous and authenticated inserts to bookings"
on public.bookings for insert
with check (true);

-- 2. Chỉ cho phép Admin hoặc chính User đọc thông tin lịch hẹn của họ
create policy "Allow users to read their own bookings"
on public.bookings for select
using (auth.uid() = profile_id);

-- 3. Kích hoạt extension pg_net để gọi Webhook
create extension if not exists pg_net;

-- 4. Hàm trigger gọi Edge Function send-booking-email
create or replace function public.handle_new_booking()
returns trigger as $$
declare
  request_id bigint;
begin
  -- Gọi HTTP POST đến Edge Function của Supabase để gửi email thông báo.
  -- Lưu ý: Bạn cần thay thế 'PROJECT_REF' bằng mã tham chiếu dự án Supabase của bạn.
  select net.http_post(
    url := 'https://PROJECT_REF.supabase.co/functions/v1/send-booking-email'::text,
    body := jsonb_build_object('record', row_to_json(new))::jsonb,
    headers := '{"Content-Type": "application/json"}'::jsonb
  ) into request_id;
  return new;
end;
$$ language plpgsql security definer;

-- 5. Trigger kích hoạt hàm gửi email sau khi chèn lịch hẹn mới
create or replace trigger on_booking_inserted
  after insert on public.bookings
  for each row execute procedure public.handle_new_booking();
