-- =======================================================
-- HOCZITA: LEARNING PROGRESS TABLE & RLS POLICIES
-- Bảng theo dõi tiến độ học tập liên tục (Toán & Tiếng Anh)
-- =======================================================

create table if not exists public.learning_progress (
    id bigint generated by default as identity primary key,
    profile_id uuid references public.profiles(id) on delete cascade not null,
    subject text not null,       -- 'math_counting', 'math_ops', 'english_basic_flashcard', 'english_advanced_flashcard'
    topic text default 'all',    -- 'all', 'animal', 'fruits', 'vegatable', ...
    total_practiced integer default 0, -- tổng số câu đã làm / thẻ đã lật
    correct_count integer default 0,   -- số câu làm đúng
    learned_items jsonb default '[]'::jsonb, -- danh sách từ/dạng bài đã học
    last_practiced_date date default current_date,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(profile_id, subject, topic)
);

-- Kích hoạt Row Level Security (RLS) bảo vệ dữ liệu
alter table public.learning_progress enable row level security;

-- Chính sách: Mỗi người dùng có toàn quyền xem và cập nhật tiến độ của chính mình
drop policy if exists "Users can manage their own learning progress" on public.learning_progress;
create policy "Users can manage their own learning progress"
  on public.learning_progress for all
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);
